---
title: "dplyr_exo"
author: "Marine"
format: html
---
```{r}
#| message: false
here::i_am("exo_dplyr.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
```

## Exercice 1:

```{r}
bank<- vroom(here("Data","bank-full.csv"))
```

### Question 1: 
```{r}
print(colnames(bank))
```
### Question 2: 
```{r}
print(dim(bank))
```

### Question 3: 
```{r}
bank %>% summary()
```
You have to tell which column and which type of summary you want. 


## Exercise 2

### Question 1: 
```{r}
bank %>% filter(age>50)
```

### Question 2: 
```{r}
bank %>% filter(marital== "married" & education== "secondary")
```
### Question 3:
```{r}
bank %>% filter(age<25 & marital=="single" & education=="tertiary")%>% summary()
```
## Exercise 3:

### Question 1: 
```{r}
bank %>% select(age) %>% summary()
bank %>% pull(age) %>% summary()
```
One is in vertical the other in horizontal. 

### Question 2:
```{r}
bank %>% select(where(is.numeric)) %>% summary()
```
### Question 3: 
```{r}
summarise(bank, median(age))
```

## Exercise 4 
```{r}
life<- vroom(here("Data","life-expectancy-at-birth-who.csv"))
```
### Question 1: 
```{r}
life <-
  life |>
  mutate(diff= Male-Female) 
```

### Question 2:
```{r}
life <-
  life |>
  mutate(reladiff= diff/`Both sexes`) 
```

## Exercise 5: 

### Question 1: 
```{r}
life <-
  life |>
  mutate(X= Female- median(Female)) 
```

### Question 2: 
```{r}
life <-
  life |>
  mutate(Y= Male- (mean(Male)/sd(Male)))
```

### Question 3: 
```{r}
life %>% mutate(Atypical= if_else(`Both sexes`>(median(`Both sexes`)+2*sd(`Both sexes`))|`Both sexes`<(median(`Both sexes`)-2*sd(`Both sexes`)), TRUE, FALSE ))
life %>% 
  filter(Year ==2019)%>%
  mutate(Atypical= if_else(`Both sexes`>(median(`Both sexes`)+2*sd(`Both sexes`))|`Both sexes`<(median(`Both sexes`)-2*sd(`Both sexes`)), TRUE, FALSE ))
```
## Exercise 6: 

### Question 1: 
```{r}
bank %>% summarise(mean(age), median(age))
```
### Question 2: 
```{r}
life %>%
  filter(Year==2015)%>%
  summarise(max(Male), min(Male), max(Female), min(Female))
```

